import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { lovable } from "@/integrations/lovable";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Wordmark } from "@/components/store-shell";

export const Route = createFileRoute("/auth")({ validateSearch: (search: Record<string, unknown>) => ({ redirect: typeof search.redirect === "string" && search.redirect.startsWith("/") ? search.redirect : "/admin" }), head: () => ({ meta: [{ title: "Acesso administrativo — CORRES DO ZK" }, { name: "description", content: "Acesso privado à administração da CORRES DO ZK." }, { property: "og:title", content: "Acesso administrativo — CORRES DO ZK" }, { property: "og:description", content: "Área privada da loja CORRES DO ZK." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: AuthPage });
function AuthPage() {
  const { redirect } = Route.useSearch(); const navigate = useNavigate();
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [mode, setMode] = useState<"login" | "signup">("login"); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(e: React.FormEvent) { e.preventDefault(); setLoading(true); setMessage(""); const result = mode === "login" ? await supabase.auth.signInWithPassword({ email, password }) : await supabase.auth.signUp({ email, password, options: { emailRedirectTo: `${window.location.origin}/auth?redirect=${encodeURIComponent(redirect)}` } }); setLoading(false); if (result.error) return setMessage(result.error.message); if (result.data.session) navigate({ to: redirect }); else setMessage("Confira seu e-mail para confirmar a conta."); }
  async function google() { sessionStorage.setItem("corres-auth-redirect", redirect); const result = await lovable.auth.signInWithOAuth("google", { redirect_uri: `${window.location.origin}/auth?redirect=${encodeURIComponent(redirect)}` }); if (result.error) setMessage(result.error.message); else if (!result.redirected) navigate({ to: redirect }); }
  return <main className="grid min-h-screen place-items-center bg-surface px-4"><div className="w-full max-w-md border border-border bg-background p-6 md:p-10"><Wordmark /><p className="eyebrow mt-10">PAINEL PRIVADO</p><h1 className="display-sm mt-3">{mode === "login" ? "ENTRAR" : "CRIAR CONTA"}</h1><form className="mt-8 grid gap-5" onSubmit={submit}><div><Label htmlFor="email">E-mail</Label><Input id="email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></div><div><Label htmlFor="password">Senha</Label><Input id="password" type="password" minLength={8} value={password} onChange={(e) => setPassword(e.target.value)} required /></div>{message && <p className="text-sm text-primary">{message}</p>}<Button size="lg" disabled={loading}>{loading ? "AGUARDE..." : mode === "login" ? "ENTRAR" : "CRIAR CONTA"}</Button></form><Button variant="outline" size="lg" className="mt-3 w-full" onClick={google}>CONTINUAR COM GOOGLE</Button><button className="mt-6 w-full text-xs font-bold uppercase text-muted-foreground" onClick={() => setMode(mode === "login" ? "signup" : "login")}>{mode === "login" ? "Ainda não tenho conta" : "Já tenho conta"}</button><p className="mt-6 border-t border-border pt-4 text-xs leading-5 text-muted-foreground">Criar uma conta não libera o painel automaticamente. A função administrativa deve ser concedida com segurança.</p></div></main>;
}